version: 2
jobs:
  build:
    working_directory: ~/aerogear
    docker:
      # Node 8 LTS
      - image: circleci/node:carbon
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - run:
          name: install-dependencies
          command: npm install
      - run:
          name: clone-sdk
          command: git clone --depth 1 https://github.com/aerogear/aerogear-js-sdk sdk
      - run:
          name: run build
          working_directory: ./sdk
          command: npm i && npm run bootstrap && npm run build
      - run:
          name: link-sdk
          command: ln -s ./sdk/packages/auth node_modules/@aerogear/auth && ln -s ./sdk/packages/core node_modules/@aerogear/core
      - run:
          name: run build
          command: npm run build
